/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atm.ui;

import com.atm.dao.TransactionDAO;
import com.atm.ui.TrendChart;
import java.util.List;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import java.io.File;
/**
 * 
 *
 * @author bhaskarjoshi
 */
public class CheckBalancePanel extends javax.swing.JPanel {
    private String currentAccountNumber;
    private double actualBalance = 0.0; // Added to store the numeric value
    private boolean isHidden = false;   // Added for toggle state
    /**
     * Creates new form CheckBalancePanel
     */
    public CheckBalancePanel(String accNum) {
    this.currentAccountNumber = accNum;
    
    // 1. Initialize components first (Crucial to avoid NullPointerException)
    initComponents();
    
    // 2. Initial UI Setup (Styling for high contrast)
    pbAtmLimit.setForeground(new java.awt.Color(255, 255, 255)); 

    pbAtmLimit.setOpaque(true);
    pbAtmLimit.setStringPainted(false); // Hide default percentage text

    pbPosLimit.setForeground(new java.awt.Color(255, 255, 255));

    pbPosLimit.setOpaque(true);
    pbPosLimit.setStringPainted(false);
    
    populateSecurityNotice();

    // 3. Data Fetching from DAO
    com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
    // Use getAccountSummary because it returns 'limit' and 'type'
    java.util.Map<String, Object> details = accDAO.getAccountSummary(currentAccountNumber);
    
    if (details != null && details.containsKey("balance") && details.containsKey("limit")) {
        // Retrieve values as Wrapper Objects to avoid primitive crash
        actualBalance = (Double) details.get("balance");
        String type = (String) details.get("type");
        Double totalLimit = (Double) details.get("limit");
        
        // Update Labels
        jLabel1.setText("ACCOUNT SUMMARY : " + type.toUpperCase() + " TYPE");
        lblAmountDisplay.setText("₹" + String.format("%.2f", actualBalance));
        
        // 4. Daily Limit Status Logic
        com.atm.dao.TransactionDAO transDAO = new com.atm.dao.TransactionDAO();
        double todaySpent = transDAO.getTodayWithdrawalTotal(currentAccountNumber);
        
        // Update ATM Progress Bar and Text
        pbAtmLimit.setMinimum(0);
        pbAtmLimit.setMaximum(totalLimit.intValue());
        pbAtmLimit.setValue((int) todaySpent);
        lblAtmLimitText.setText(String.format("₹%.2f / ₹%.2f", todaySpent, totalLimit));
        
        // Update POS Progress Bar (Static example for design)
        pbPosLimit.setMaximum(5000);
        pbPosLimit.setValue(0);
        lblPosLimitText.setText("₹0.00 / ₹5000.00");
        
    } else {
        // Fallback for missing account data
        lblAmountDisplay.setText("ACCOUNT ERROR");
        System.err.println("No DB data found for account: " + currentAccountNumber);
    }
    
    // 5. Trend Graph Logic
    try {
        com.atm.dao.TransactionDAO trendDAO = new com.atm.dao.TransactionDAO();
        List<Double> trendData = trendDAO.getBalanceTrend(currentAccountNumber);

        if (trendData != null && !trendData.isEmpty()) {
            TrendChart myChart = new TrendChart(trendData);
            
            // Layout management for the container
            trendContainer.setLayout(new BorderLayout()); 
            trendContainer.removeAll(); 
            trendContainer.add(myChart, BorderLayout.CENTER);
            
            // Refresh visuals
            trendContainer.revalidate();
            trendContainer.repaint();
        }
    } catch (Exception e) {
        System.err.println("Error loading trend graph: " + e.getMessage());
    }

    // 6. Interaction Setup
    lblHideToggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

    
    private void toggleBalance() {
        if (!isHidden) {
            lblAmountDisplay.setText("********");
            lblHideToggle.setText("👁 Show Balance");
            isHidden = true;
        } else {
            lblAmountDisplay.setText("₹" + String.format("%.2f", actualBalance));
            lblHideToggle.setText("👁 Hide Balance");
            isHidden = false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkBalance = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        balanceBlockContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblAmountDisplay = new javax.swing.JLabel();
        btnPrintReceipt = new javax.swing.JButton();
        lblHideToggle = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        trendContainer = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pbAtmLimit = new javax.swing.JProgressBar();
        pbPosLimit = new javax.swing.JProgressBar();
        lblAtmLimitText = new javax.swing.JLabel();
        lblPosLimitText = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(830, 620));
        setSize(new java.awt.Dimension(830, 620));

        checkBalance.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(801, 50));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCOUNT SUMMARY : SAVING TYPE");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        checkBalance.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(25, 556));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        checkBalance.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(362, 558));

        balanceBlockContainer.setBackground(new java.awt.Color(51, 102, 255));
        balanceBlockContainer.setPreferredSize(new java.awt.Dimension(362, 265));

        jLabel2.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CURRENT AVAILABLE BALANCE");

        lblAmountDisplay.setBackground(new java.awt.Color(51, 102, 255));
        lblAmountDisplay.setFont(new java.awt.Font("Tamil Sangam MN", 1, 22)); // NOI18N
        lblAmountDisplay.setForeground(new java.awt.Color(51, 153, 0));
        lblAmountDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnPrintReceipt.setBackground(new java.awt.Color(153, 204, 255));
        btnPrintReceipt.setFont(new java.awt.Font("Tamil Sangam MN", 1, 16)); // NOI18N
        btnPrintReceipt.setForeground(new java.awt.Color(0, 51, 51));
        btnPrintReceipt.setText("PRINT RECEIPT");
        btnPrintReceipt.addActionListener(this::btnPrintReceiptActionPerformed);

        lblHideToggle.setBackground(new java.awt.Color(51, 102, 255));
        lblHideToggle.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblHideToggle.setForeground(new java.awt.Color(204, 255, 255));
        lblHideToggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHideToggle.setText("👁 Hide Balance");
        lblHideToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideToggleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout balanceBlockContainerLayout = new javax.swing.GroupLayout(balanceBlockContainer);
        balanceBlockContainer.setLayout(balanceBlockContainerLayout);
        balanceBlockContainerLayout.setHorizontalGroup(
            balanceBlockContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                .addGroup(balanceBlockContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                        .addGroup(balanceBlockContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblAmountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(lblHideToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        balanceBlockContainerLayout.setVerticalGroup(
            balanceBlockContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceBlockContainerLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblAmountDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHideToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel9.setPreferredSize(new java.awt.Dimension(362, 265));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(362, 40));

        jLabel4.setBackground(new java.awt.Color(51, 102, 255));
        jLabel4.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FINANCIAL TREND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel1, java.awt.BorderLayout.NORTH);

        trendContainer.setBackground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout trendContainerLayout = new javax.swing.GroupLayout(trendContainer);
        trendContainer.setLayout(trendContainerLayout);
        trendContainerLayout.setHorizontalGroup(
            trendContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        trendContainerLayout.setVerticalGroup(
            trendContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jPanel9.add(trendContainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(balanceBlockContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(balanceBlockContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(25, 558));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jPanel13.setBackground(new java.awt.Color(51, 102, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(362, 265));

        jLabel3.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DAILY LIMIT STATUS ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ATM WITHDRAWALS");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("POS TRANSACTIONS");

        pbAtmLimit.setBackground(new java.awt.Color(51, 102, 255));
        pbAtmLimit.setForeground(new java.awt.Color(255, 255, 255));

        pbPosLimit.setBackground(new java.awt.Color(51, 102, 255));
        pbPosLimit.setForeground(new java.awt.Color(255, 255, 255));

        lblAtmLimitText.setBackground(new java.awt.Color(51, 102, 255));
        lblAtmLimitText.setFont(new java.awt.Font("Tamil MN", 0, 13)); // NOI18N
        lblAtmLimitText.setForeground(new java.awt.Color(204, 255, 255));

        lblPosLimitText.setBackground(new java.awt.Color(51, 102, 255));
        lblPosLimitText.setFont(new java.awt.Font("Tamil MN", 0, 13)); // NOI18N
        lblPosLimitText.setForeground(new java.awt.Color(204, 255, 255));
        lblPosLimitText.setPreferredSize(new java.awt.Dimension(42, 21));
        lblPosLimitText.setSize(new java.awt.Dimension(42, 21));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pbPosLimit, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addComponent(pbAtmLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblAtmLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPosLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbAtmLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtmLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbPosLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPosLimitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel14.setBackground(new java.awt.Color(51, 102, 255));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(362, 265));

        jLabel5.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SECURITY NOTICE");

        jLabel6.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 0));
        jLabel6.setText("🛡   ACCOUNT ACTIVE AND SECURE");

        jLabel9.setFont(new java.awt.Font("Tamil MN", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LAST LOGIN DETAILS:");

        lbl1.setBackground(new java.awt.Color(51, 102, 255));
        lbl1.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));

        lbl2.setBackground(new java.awt.Color(51, 102, 255));
        lbl2.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));

        lbl3.setBackground(new java.awt.Color(51, 102, 255));
        lbl3.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));

        lbl4.setBackground(new java.awt.Color(51, 102, 255));
        lbl4.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(25, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel10.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel10, java.awt.BorderLayout.CENTER);

        checkBalance.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(checkBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHideToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideToggleMouseClicked
        // TODO add your handling code here:
        toggleBalance();
    }//GEN-LAST:event_lblHideToggleMouseClicked

    
    private void populateSecurityNotice() {
    com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
    java.util.List<String> loginData = accDAO.getLastLogins(currentAccountNumber);

    // Reset labels first
    lbl1.setText("No recent activity");
    lbl2.setText("");
    lbl3.setText("");
    lbl4.setText("");

    // Populate based on available data
    if (loginData.size() >= 1) lbl1.setText("• Latest: " + loginData.get(0));
    if (loginData.size() >= 2) lbl2.setText("• Previous: " + loginData.get(1));
    if (loginData.size() >= 3) lbl3.setText("• History: " + loginData.get(2));
    if (loginData.size() >= 4) lbl4.setText("• History: " + loginData.get(3));
}
    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        // TODO add your handling code here:
        try {
        com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
        java.util.Map<String, Object> details = accDAO.getAccountDetails(currentAccountNumber);

        com.atm.service.ReceiptService service = new com.atm.service.ReceiptService();
        String path = service.generateBalanceReceipt(currentAccountNumber, details);

        if (path != null) {
            // Show Success Message
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Receipt Saved to: " + path, 
                "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // AUTO-OPEN THE PDF
            try {
                File pdfFile = new File(path);
                if (pdfFile.exists()) {
                    if (java.awt.Desktop.isDesktopSupported()) {
                        java.awt.Desktop.getDesktop().open(pdfFile);
                    } else {
                        System.out.println("AWT Desktop is not supported on this system.");
                    }
                }
            } catch (Exception ex) {
                System.err.println("Error opening PDF: " + ex.getMessage());
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error generating PDF.", "Error", 0);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    public static void main(String[] args) {
    JFrame frame = new JFrame("Testing Balance Panel");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setSize(850, 650);
    
    // Create the panel with a dummy account number from your DB
    CheckBalancePanel panel = new CheckBalancePanel("1234567890");
    
    frame.add(panel);
    frame.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel balanceBlockContainer;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JPanel checkBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lblAmountDisplay;
    private javax.swing.JLabel lblAtmLimitText;
    private javax.swing.JLabel lblHideToggle;
    private javax.swing.JLabel lblPosLimitText;
    private javax.swing.JProgressBar pbAtmLimit;
    private javax.swing.JProgressBar pbPosLimit;
    private javax.swing.JPanel trendContainer;
    // End of variables declaration//GEN-END:variables
}
