/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atm.ui;

import javax.swing.JOptionPane;

import java.util.Map;
import java.util.HashMap;

import java.awt.*;

import java.io.File;

/**
 *
 * @author bhaskarjoshi
 */
public class DepositPanel extends javax.swing.JPanel {
    private String accountNumber;
    private double currentBalance = 0.0;
    /**
     * Creates new form DepositPanel
     */
    
    public DepositPanel(String accNum) {
        this.accountNumber = accNum;
        initComponents();
        // For the Cancel Button
btnCancel.setContentAreaFilled(true);
btnCancel.setBorderPainted(false); // Often helps the background color pop
btnCancel.setOpaque(true);

// For the Confirm Button
btnConfirmWithdraw.setContentAreaFilled(true);
btnConfirmWithdraw.setBorderPainted(false);
btnConfirmWithdraw.setOpaque(true);
        loadInitialData();
        setupLiveImpact();
    }
    
    public DepositPanel() {
        initComponents();
    }

    
    private void loadInitialData() {
        com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
        currentBalance = accDAO.getBalance(accountNumber);
        lblCurrentBalance.setText(String.format("₹ %.2f", currentBalance));
        lblNewBalance.setText(String.format("₹ %.2f", currentBalance));
        lblLiveWithdraw.setText("₹ 0.00"); // This represents the deposit amount here
    }
    
    private void setupLiveImpact() {
        txtWithdrawAmount.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { updateLabels(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { updateLabels(); }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { updateLabels(); }

            private void updateLabels() {
                try {
                    String text = txtWithdrawAmount.getText();
                    double amount = text.isEmpty() ? 0 : Double.parseDouble(text);
                    lblLiveWithdraw.setText(String.format("₹ %.2f", amount));
                    
                    // UPDATED FOR DEPOSIT: Add currentBalance + amount
                    double depositBalance = currentBalance + amount;
                    lblNewBalance.setText(String.format("₹ %.2f", depositBalance));
                    
                    // Always Green for Deposit
                    lblNewBalance.setForeground(new java.awt.Color(51, 153, 0)); 
                } catch (NumberFormatException e) {
                    lblLiveWithdraw.setText("Invalid Amount");
                }
            }
        });
    }
    
    private void setAmount(String amount) {
        txtWithdrawAmount.setText(amount);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtWithdrawAmount = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnQuick100 = new javax.swing.JLabel();
        btnQuick500 = new javax.swing.JLabel();
        btnQuick1k = new javax.swing.JLabel();
        btnQuick15k = new javax.swing.JLabel();
        btnQuick3k = new javax.swing.JLabel();
        btnQuick25k = new javax.swing.JLabel();
        btnQuick2k = new javax.swing.JLabel();
        btnQuick35k = new javax.swing.JLabel();
        btnQuick4k = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblCurrentBalance = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblLiveWithdraw = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblNewBalance = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnConfirmWithdraw = new javax.swing.JButton();

        setPreferredSize(null);
        setSize(new java.awt.Dimension(830, 620));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(25, 620));
        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(805, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(805, 50));

        jLabel1.setFont(new java.awt.Font("Tamil MN", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CASH DEPOSIT");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setPreferredSize(new java.awt.Dimension(805, 480));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(452, 480));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(51, 102, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setPreferredSize(new java.awt.Dimension(452, 50));

        jLabel2.setFont(new java.awt.Font("Tamil MN", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SMART DENOMINATION SELECTION");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.add(jPanel11, java.awt.BorderLayout.NORTH);

        jPanel13.setBackground(new java.awt.Color(204, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(452, 60));

        txtWithdrawAmount.setBackground(new java.awt.Color(204, 204, 255));
        txtWithdrawAmount.setFont(new java.awt.Font("Telugu MN", 1, 20)); // NOI18N
        txtWithdrawAmount.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtWithdrawAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtWithdrawAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel16.setBackground(new java.awt.Color(204, 255, 255));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tamil MN", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("QUICK CASH");
        jLabel4.setOpaque(true);

        btnQuick100.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick100.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick100.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick100.setText("₹ 100");
        btnQuick100.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick100.setOpaque(true);
        btnQuick100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick100MouseClicked(evt);
            }
        });

        btnQuick500.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick500.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick500.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick500.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick500.setText("₹ 500");
        btnQuick500.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick500.setOpaque(true);
        btnQuick500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick500MouseClicked(evt);
            }
        });

        btnQuick1k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick1k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick1k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick1k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick1k.setText("₹ 1000");
        btnQuick1k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick1k.setOpaque(true);
        btnQuick1k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick1kMouseClicked(evt);
            }
        });

        btnQuick15k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick15k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick15k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick15k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick15k.setText("₹ 1500");
        btnQuick15k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick15k.setOpaque(true);
        btnQuick15k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick15kMouseClicked(evt);
            }
        });

        btnQuick3k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick3k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick3k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick3k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick3k.setText("₹ 3000");
        btnQuick3k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick3k.setOpaque(true);
        btnQuick3k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick3kMouseClicked(evt);
            }
        });

        btnQuick25k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick25k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick25k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick25k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick25k.setText("₹ 2500");
        btnQuick25k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick25k.setOpaque(true);
        btnQuick25k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick25kMouseClicked(evt);
            }
        });

        btnQuick2k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick2k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick2k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick2k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick2k.setText("₹ 2000");
        btnQuick2k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick2k.setOpaque(true);
        btnQuick2k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick2kMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuick2kMouseEntered(evt);
            }
        });

        btnQuick35k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick35k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick35k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick35k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick35k.setText("₹ 3500");
        btnQuick35k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick35k.setOpaque(true);
        btnQuick35k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick35kMouseClicked(evt);
            }
        });

        btnQuick4k.setBackground(new java.awt.Color(51, 102, 255));
        btnQuick4k.setFont(new java.awt.Font("Telugu MN", 1, 17)); // NOI18N
        btnQuick4k.setForeground(new java.awt.Color(255, 255, 255));
        btnQuick4k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuick4k.setText("₹ 4000");
        btnQuick4k.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnQuick4k.setOpaque(true);
        btnQuick4k.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuick4kMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuick100, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnQuick3k, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(btnQuick15k, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuick500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick2k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick35k, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQuick1k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick25k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick4k, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuick100, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnQuick1k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuick15k, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuick2k, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuick25k, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnQuick3k, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnQuick35k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuick4k, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(51, 102, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setPreferredSize(new java.awt.Dimension(353, 50));

        jLabel3.setFont(new java.awt.Font("Tamil MN", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LIVE IMPACT CALCULATOR");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.add(jPanel12, java.awt.BorderLayout.NORTH);

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setBackground(new java.awt.Color(51, 102, 255));
        jLabel14.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CURRENT BALANCE");
        jLabel14.setOpaque(true);

        lblCurrentBalance.setBackground(new java.awt.Color(204, 204, 225));
        lblCurrentBalance.setFont(new java.awt.Font("Telugu MN", 1, 15)); // NOI18N
        lblCurrentBalance.setForeground(new java.awt.Color(0, 51, 51));
        lblCurrentBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentBalance.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(204, 255, 255));
        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("↓");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(51, 102, 255));
        jLabel17.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("WITHDRAW");
        jLabel17.setOpaque(true);

        lblLiveWithdraw.setBackground(new java.awt.Color(204, 204, 225));
        lblLiveWithdraw.setFont(new java.awt.Font("Telugu MN", 1, 15)); // NOI18N
        lblLiveWithdraw.setForeground(new java.awt.Color(51, 153, 0));
        lblLiveWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiveWithdraw.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(51, 102, 255));
        jLabel19.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("NEW BALANCE");
        jLabel19.setOpaque(true);

        lblNewBalance.setBackground(new java.awt.Color(204, 204, 225));
        lblNewBalance.setFont(new java.awt.Font("Tamil MN", 1, 15)); // NOI18N
        lblNewBalance.setForeground(new java.awt.Color(51, 153, 0));
        lblNewBalance.setOpaque(true);

        jLabel21.setBackground(new java.awt.Color(204, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tamil MN", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 102, 255));
        jLabel21.setText("🛡️ Funds Available. Transaction Secured");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNewBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(70, 70, 70))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(lblCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(lblLiveWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLiveWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel10.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel18.setBackground(new java.awt.Color(204, 255, 255));
        jPanel18.setLayout(new java.awt.GridBagLayout());

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Telugu MN", 1, 20)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("CANCEL");
        btnCancel.setOpaque(true);
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 147, 6, 0);
        jPanel18.add(btnCancel, gridBagConstraints);

        btnConfirmWithdraw.setBackground(new java.awt.Color(51, 153, 0));
        btnConfirmWithdraw.setFont(new java.awt.Font("Telugu MN", 1, 20)); // NOI18N
        btnConfirmWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmWithdraw.setText("CONFIRM DEPOSIT");
        btnConfirmWithdraw.setOpaque(true);
        btnConfirmWithdraw.addActionListener(this::btnConfirmWithdrawActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 67, 6, 129);
        jPanel18.add(btnConfirmWithdraw, gridBagConstraints);

        jPanel7.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuick100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick100MouseClicked
        // TODO add your handling code here:
        setAmount("100");
    }//GEN-LAST:event_btnQuick100MouseClicked

    private void btnQuick500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick500MouseClicked
        // TODO add your handling code here:
        setAmount("500");
    }//GEN-LAST:event_btnQuick500MouseClicked

    private void btnQuick1kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick1kMouseClicked
        // TODO add your handling code here:
        setAmount("1000");
    }//GEN-LAST:event_btnQuick1kMouseClicked

    private void btnQuick15kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick15kMouseClicked
        // TODO add your handling code here:
        setAmount("1500");
    }//GEN-LAST:event_btnQuick15kMouseClicked

    private void btnQuick3kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick3kMouseClicked
        // TODO add your handling code here:
        setAmount("3000");
    }//GEN-LAST:event_btnQuick3kMouseClicked

    private void btnQuick25kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick25kMouseClicked
        // TODO add your handling code here:
        setAmount("2500");
    }//GEN-LAST:event_btnQuick25kMouseClicked

    private void btnQuick2kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick2kMouseClicked
        // TODO add your handling code here:
        setAmount("2000");
    }//GEN-LAST:event_btnQuick2kMouseClicked

    private void btnQuick2kMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick2kMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnQuick2kMouseEntered

    private void btnQuick35kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick35kMouseClicked
        // TODO add your handling code here:
        setAmount("3500");
    }//GEN-LAST:event_btnQuick35kMouseClicked

    private void btnQuick4kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuick4kMouseClicked
        // TODO add your handling code here:
        setAmount("4000");
    }//GEN-LAST:event_btnQuick4kMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtWithdrawAmount.setText("");
    }                                         

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame f = new javax.swing.JFrame();
            f.add(new DepositPanel("1234567890"));
            f.setSize(830, 620);
            f.setVisible(true);
        });
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmWithdrawActionPerformed
        // TODO add your handling code here:
        try {
            double amount = Double.parseDouble(txtWithdrawAmount.getText());
            
            // 1. Basic Validation
            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid amount to deposit.");
                return;
            }

            com.atm.dao.TransactionDAO transDAO = new com.atm.dao.TransactionDAO();
            com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
            
            // 2. Perform Deposit (Addition)
            double newBalance = currentBalance + amount;
            
            if (accDAO.updateBalance(accountNumber, newBalance)) {
                // IMPORTANT: Record as 'Deposit'
                transDAO.recordTransaction(accountNumber, "Deposit", amount, newBalance);
                
                JOptionPane.showMessageDialog(this, "Deposit Successful!");

                // --- RECEIPT LOGIC ---
                try {
                    com.atm.service.ReceiptService service = new com.atm.service.ReceiptService();
                    Map<String, Object> receiptData = new HashMap<>();
                    receiptData.put("amount", amount);
                    receiptData.put("new_balance", newBalance);
                    receiptData.put("type", "Deposit");

                   String path = service.generateTransactionReceipt(accountNumber, receiptData);

                    if (path != null) {
                        File pdfFile = new File(path);
                        if (pdfFile.exists() && Desktop.isDesktopSupported()) {
                            Desktop.getDesktop().open(pdfFile);
                        }
                    }
                } catch (Exception ex) {
                    System.err.println("Receipt Error: " + ex.getMessage());
                }

                loadInitialData(); // Refresh UI
                txtWithdrawAmount.setText("");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric amount.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmWithdrawActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmWithdraw;
    private javax.swing.JLabel btnQuick100;
    private javax.swing.JLabel btnQuick15k;
    private javax.swing.JLabel btnQuick1k;
    private javax.swing.JLabel btnQuick25k;
    private javax.swing.JLabel btnQuick2k;
    private javax.swing.JLabel btnQuick35k;
    private javax.swing.JLabel btnQuick3k;
    private javax.swing.JLabel btnQuick4k;
    private javax.swing.JLabel btnQuick500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblLiveWithdraw;
    private javax.swing.JLabel lblNewBalance;
    private javax.swing.JTextField txtWithdrawAmount;
    // End of variables declaration//GEN-END:variables
}
