/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atm.ui;
import com.atm.dao.AccountDAO;
import java.util.Map;
/**
 *
 * @author bhaskarjoshi
 */
public class MainFrame extends javax.swing.JFrame {
    private String currentAccountNumber;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame(String accNum) {
        this.currentAccountNumber = accNum; // Store the passed account number
        initComponents();
        this.setLocationRelativeTo(null);
        setScaledLogo();
        populateHeaderData(accNum); // Pass it to the header function
    }
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setScaledLogo();
        
        
    }
    private void populateHeaderData(String accNum) {
        try {
            com.atm.dao.AccountDAO accDAO = new com.atm.dao.AccountDAO();
            Map<String, Object> details = accDAO.getAccountSummary(accNum);

            if (details != null && !details.isEmpty()) {
                String ownerName = details.get("name") != null ? (String) details.get("name") : "User";
                lblWelcome.setText("WELCOME, " + ownerName.toUpperCase());

                String maskedAcc = "ACCOUNT NUMBER: " +  accNum;
                lblAccountNumber.setText(maskedAcc);
            }
        } catch (Exception e) {
            System.err.println("Error populating header: " + e.getMessage());
            lblWelcome.setText("Welcome, Guest");
            lblAccountNumber.setText("A/C No: " + accNum);
        }
    }
    private void setScaledLogo() {
    try {
        // 1. Updated path to look for atm_logo.png
        java.net.URL imgUrl = getClass().getResource("/resources/atm_logo.png");
        
        if (imgUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgUrl);
            
            // 2. Scale it to exactly 75x75 with smooth filtering
            java.awt.Image img = icon.getImage();
            java.awt.Image scaledImg = img.getScaledInstance(75, 75, java.awt.Image.SCALE_SMOOTH);
            
            // 3. Apply to label
            if (lblLogo != null) {
                lblLogo.setIcon(new javax.swing.ImageIcon(scaledImg));
                lblLogo.setText(""); // Clears any placeholder text like "jLabel1"
            }
        } else {
            System.err.println("Error: atm_logo.png not found in /com/atm/resources/");
            // Optional: Set a default text if image is missing
            lblLogo.setText("ATM LOGO");
        }
    } catch (Exception e) {
        System.err.println("Logo Scaling Error: " + e.getMessage());
        e.printStackTrace();
    }
}

    
    private void showPanel(javax.swing.JPanel panel) {
    pnlMainContent.removeAll();
    pnlMainContent.setLayout(new java.awt.BorderLayout());
    pnlMainContent.add(panel, java.awt.BorderLayout.CENTER);
    pnlMainContent.revalidate();
    pnlMainContent.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topmostpanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        lblMenuCheckBalance = new javax.swing.JLabel();
        lblMenuWithdraw = new javax.swing.JLabel();
        lblMenuDeposit = new javax.swing.JLabel();
        lblMenuLogout = new javax.swing.JLabel();
        lblMenuHistory = new javax.swing.JLabel();
        pnlMainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1025, 730));

        topmostpanel.setBackground(new java.awt.Color(204, 255, 255));
        topmostpanel.setPreferredSize(new java.awt.Dimension(1030, 100));
        topmostpanel.setSize(new java.awt.Dimension(1030, 100));

        lblLogo.setBackground(new java.awt.Color(204, 255, 255));
        lblLogo.setOpaque(true);

        lblWelcome.setBackground(new java.awt.Color(204, 255, 255));
        lblWelcome.setFont(new java.awt.Font("Tamil MN", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(51, 102, 255));
        lblWelcome.setOpaque(true);

        lblAccountNumber.setBackground(new java.awt.Color(204, 255, 255));
        lblAccountNumber.setFont(new java.awt.Font("Tamil MN", 1, 15)); // NOI18N
        lblAccountNumber.setForeground(new java.awt.Color(51, 102, 255));
        lblAccountNumber.setOpaque(true);

        javax.swing.GroupLayout topmostpanelLayout = new javax.swing.GroupLayout(topmostpanel);
        topmostpanel.setLayout(topmostpanelLayout);
        topmostpanelLayout.setHorizontalGroup(
            topmostpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topmostpanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(topmostpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        topmostpanelLayout.setVerticalGroup(
            topmostpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topmostpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topmostpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topmostpanelLayout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topmostpanelLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(topmostpanel, java.awt.BorderLayout.NORTH);

        pnlSidebar.setBackground(new java.awt.Color(204, 255, 255));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(200, 630));
        pnlSidebar.setSize(new java.awt.Dimension(200, 630));

        lblMenuCheckBalance.setBackground(new java.awt.Color(51, 102, 255));
        lblMenuCheckBalance.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblMenuCheckBalance.setForeground(new java.awt.Color(204, 255, 255));
        lblMenuCheckBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuCheckBalance.setText("CHECK BALANCE");
        lblMenuCheckBalance.setOpaque(true);
        lblMenuCheckBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuCheckBalanceMouseClicked(evt);
            }
        });

        lblMenuWithdraw.setBackground(new java.awt.Color(51, 102, 255));
        lblMenuWithdraw.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblMenuWithdraw.setForeground(new java.awt.Color(204, 255, 255));
        lblMenuWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuWithdraw.setText("WITHDRAW");
        lblMenuWithdraw.setOpaque(true);
        lblMenuWithdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuWithdrawMouseClicked(evt);
            }
        });

        lblMenuDeposit.setBackground(new java.awt.Color(51, 102, 255));
        lblMenuDeposit.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblMenuDeposit.setForeground(new java.awt.Color(204, 255, 255));
        lblMenuDeposit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuDeposit.setText("DEPOSIT");
        lblMenuDeposit.setOpaque(true);
        lblMenuDeposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuDepositMouseClicked(evt);
            }
        });

        lblMenuLogout.setBackground(new java.awt.Color(51, 102, 255));
        lblMenuLogout.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblMenuLogout.setForeground(new java.awt.Color(204, 255, 255));
        lblMenuLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuLogout.setText("LOGOUT");
        lblMenuLogout.setOpaque(true);
        lblMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuLogoutMouseClicked(evt);
            }
        });

        lblMenuHistory.setBackground(new java.awt.Color(51, 102, 255));
        lblMenuHistory.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        lblMenuHistory.setForeground(new java.awt.Color(204, 255, 255));
        lblMenuHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuHistory.setText("<html>TRANSACTIONS<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HISTORY</html>");
        lblMenuHistory.setOpaque(true);
        lblMenuHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuHistoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMenuHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenuDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenuWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMenuCheckBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(lblMenuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblMenuCheckBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMenuWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMenuDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMenuHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.WEST);

        pnlMainContent.setBackground(new java.awt.Color(204, 255, 255));
        pnlMainContent.setPreferredSize(new java.awt.Dimension(830, 620));
        pnlMainContent.setSize(new java.awt.Dimension(830, 620));
        pnlMainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlMainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuCheckBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuCheckBalanceMouseClicked
        // TODO add your handling code here:
        showPanel(new CheckBalancePanel(currentAccountNumber));
    }//GEN-LAST:event_lblMenuCheckBalanceMouseClicked

    private void lblMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuLogoutMouseClicked
        // TODO add your handling code here:
        // 1. Confirm with the user (Optional but professional)
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", 
            "Logout Confirmation", 
            javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        // 2. Clear the session data
        this.currentAccountNumber = null;
        
        // 3. Open the Login Frame
        new LoginFrame().setVisible(true);
        
        // 4. Close (destroy) the current MainFrame
        this.dispose();
    }
    }//GEN-LAST:event_lblMenuLogoutMouseClicked

    private void lblMenuWithdrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuWithdrawMouseClicked
        // TODO add your handling code here:
        if (currentAccountNumber != null) {
        // 1. Create the new WithdrawPanel and pass the current account number
        WithdrawPanel withdrawPanel = new WithdrawPanel(currentAccountNumber);
        
        // 2. Pass it to the swapper method
        showPanel(withdrawPanel);
    } else {
        System.err.println("Error: Account Number not found in MainFrame.");
    }
    }//GEN-LAST:event_lblMenuWithdrawMouseClicked

    private void lblMenuDepositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuDepositMouseClicked
        // TODO add your handling code here:
        showPanel(new DepositPanel(currentAccountNumber));
    }//GEN-LAST:event_lblMenuDepositMouseClicked

    private void lblMenuHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuHistoryMouseClicked
        // TODO add your handling code here:
        showPanel(new TransactionHistory(currentAccountNumber));
    }//GEN-LAST:event_lblMenuHistoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame("1234567890").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuCheckBalance;
    private javax.swing.JLabel lblMenuDeposit;
    private javax.swing.JLabel lblMenuHistory;
    private javax.swing.JLabel lblMenuLogout;
    private javax.swing.JLabel lblMenuWithdraw;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel topmostpanel;
    // End of variables declaration//GEN-END:variables
}
