/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.atm.ui;

import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author bhaskarjoshi
 */
public class TransactionHistory extends javax.swing.JPanel {

    private String currentAccountNumber;
    /**
     * Creates new form TransactionHistory
     */
    
    public TransactionHistory(String accNum) {
    this.currentAccountNumber = accNum;
    initComponents();
    setupTableUI();
    loadTransactionTable(); // Loads the data immediately
}
    public TransactionHistory() {
        initComponents();
    }

    private void setupTableUI() {
    // 1. Get the header object from your table
    javax.swing.table.JTableHeader header = tblTransactionLog.getTableHeader();

    // 2. Set the font to Tamil MN, Bold, Size 20
    header.setFont(new java.awt.Font("Tamil MN", java.awt.Font.BOLD, 20));

    // 3. Set the text color (Foreground) to Black as requested
    header.setForeground(java.awt.Color.BLACK);

    // 4. Set Header height to fit the larger font
    header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 40));

    // 5. Setup centered renderer for data rows
    javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    
    // Apply center alignment to all data columns
    for (int i = 0; i < tblTransactionLog.getColumnCount(); i++) {
        tblTransactionLog.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // 6. Center-align the text within the Header itself
    if (header.getDefaultRenderer() instanceof javax.swing.JLabel) {
        ((javax.swing.JLabel) header.getDefaultRenderer()).setHorizontalAlignment(javax.swing.JLabel.CENTER);
    } else {
        // Fallback for some Look and Feels
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    }
    
    // 7. Set the row height for the data
    tblTransactionLog.setRowHeight(30);
    
    // 1. Force the Table itself to White
tblTransactionLog.setBackground(java.awt.Color.WHITE);

// 2. Target the Viewport (The most common cause of the grey area)
if (tblTransactionLog.getParent() instanceof javax.swing.JViewport) {
    javax.swing.JViewport viewport = (javax.swing.JViewport) tblTransactionLog.getParent();
    viewport.setBackground(java.awt.Color.WHITE);
    viewport.setOpaque(true);
}

// 3. Target the ScrollPane (The outermost container)
// Replace 'jScrollPane1' with whatever your table's ScrollPane name is
if (jScrollPane1 != null) {
    jScrollPane1.setBackground(java.awt.Color.WHITE);
    jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
    jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder()); // Optional: removes the border for a cleaner look
}

// 4. Force the table to fill the empty space
tblTransactionLog.setFillsViewportHeight(true);
}
    
    private void loadTransactionTable() {
    // 1. Get the Table Model
    DefaultTableModel model = (DefaultTableModel) tblTransactionLog.getModel();
    
    // 2. Clear existing rows so we don't duplicate data
    model.setRowCount(0);

    // 3. Fetch data from DAO
    com.atm.dao.TransactionDAO transDAO = new com.atm.dao.TransactionDAO();
    List<Object[]> history = transDAO.getFullTransactionHistory(currentAccountNumber);

    // 4. Add rows to table
    for (Object[] row : history) {
        model.addRow(row);
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactionLog = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(830, 620));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(25, 620));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(805, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(51, 102, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(805, 60));

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tamil MN", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTION LOG");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblTransactionLog.setBackground(new java.awt.Color(255, 255, 255));
        tblTransactionLog.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        tblTransactionLog.setForeground(new java.awt.Color(51, 102, 255));
        tblTransactionLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DATE/TIME", "ACTION", "AMOUNT", "BALANCE AFTER"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransactionLog);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransactionLog;
    // End of variables declaration//GEN-END:variables
}
